services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cceab_development
    ports:
      - "5433:5432"  # Map PostgreSQL default port 5432 to host port 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

  api_handler:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/cceab_development?sslmode=disable
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  validator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/cceab_development?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["./validator"]

volumes:
  pgdata:
